default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: yidao

test:
  <<: *default
  database: yidao_test

production:
  <<: *default
  database: yidao
