# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2f560c3f45fe3eb43f111a03f91a2a25c1c91fe780b3586f0e012ea853e412576a572b57eca4328201b0a7526c28116e4f0046991bc839709661cf520afb3d9

test:
  secret_key_base: f45e434dff12524078d5fe42c8f996c2fa8ca64c9a2b52900bdcf91c0762672a547e31d0ef41bbb8825ee27fed42c3c44f819e406d8e8d33c89870bc3bfd89bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
